### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by ahmedash95** [ahmedash95/laravel-facebook-poster-notification#1]
Hi @christophrumpel , this is what I've done until now . and will finished it next Friday. 

waiting your review

**Comment by christophrumpel** [comment]
Hey @ahmedash95 , great! Looks like this is going fast! Looking forward to test it and check out the code on the weekend.

**Comment by ahmedash95** [comment]
@christophrumpel  very nice , i do some updates in readme and refactoring some stauff , but i need help to write the tests for it if you have a free time

**Comment by ahmedash95** [comment]
I'm done with everything at pushed it to [The main repo](https://github.com/laravel-notification-channels/facebook-poster) . 

Thanks @christophrumpel :)
